// <auto-generated />
namespace Nicacio.MinhaApi.AcessoDados.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AjustandoCamposAluno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjustandoCamposAluno));
        
        string IMigrationMetadata.Id
        {
            get { return "201911250202418_AjustandoCamposAluno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
